//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_timeseg
    {
        public int id { get; set; }
        public string change_operator { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string create_operator { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string delete_operator { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public int status { get; set; }
        public string timeseg_name { get; set; }
        public string memo { get; set; }
        public System.DateTime sunday_start1 { get; set; }
        public Nullable<System.DateTime> sunday_end1 { get; set; }
        public Nullable<System.DateTime> sunday_start2 { get; set; }
        public Nullable<System.DateTime> sunday_end2 { get; set; }
        public Nullable<System.DateTime> sunday_start3 { get; set; }
        public Nullable<System.DateTime> sunday_end3 { get; set; }
        public Nullable<System.DateTime> monday_start1 { get; set; }
        public Nullable<System.DateTime> monday_end1 { get; set; }
        public Nullable<System.DateTime> monday_start2 { get; set; }
        public Nullable<System.DateTime> monday_end2 { get; set; }
        public Nullable<System.DateTime> monday_start3 { get; set; }
        public Nullable<System.DateTime> monday_end3 { get; set; }
        public Nullable<System.DateTime> tuesday_start1 { get; set; }
        public Nullable<System.DateTime> tuesday_end1 { get; set; }
        public Nullable<System.DateTime> tuesday_start2 { get; set; }
        public Nullable<System.DateTime> tuesday_end2 { get; set; }
        public Nullable<System.DateTime> tuesday_start3 { get; set; }
        public Nullable<System.DateTime> tuesday_end3 { get; set; }
        public Nullable<System.DateTime> wednesday_start1 { get; set; }
        public Nullable<System.DateTime> wednesday_end1 { get; set; }
        public Nullable<System.DateTime> wednesday_start2 { get; set; }
        public Nullable<System.DateTime> wednesday_end2 { get; set; }
        public Nullable<System.DateTime> wednesday_start3 { get; set; }
        public Nullable<System.DateTime> wednesday_end3 { get; set; }
        public Nullable<System.DateTime> thursday_start1 { get; set; }
        public Nullable<System.DateTime> thursday_end1 { get; set; }
        public Nullable<System.DateTime> thursday_start2 { get; set; }
        public Nullable<System.DateTime> thursday_end2 { get; set; }
        public Nullable<System.DateTime> thursday_start3 { get; set; }
        public Nullable<System.DateTime> thursday_end3 { get; set; }
        public Nullable<System.DateTime> friday_start1 { get; set; }
        public Nullable<System.DateTime> friday_end1 { get; set; }
        public Nullable<System.DateTime> friday_start2 { get; set; }
        public Nullable<System.DateTime> friday_end2 { get; set; }
        public Nullable<System.DateTime> friday_start3 { get; set; }
        public Nullable<System.DateTime> friday_end3 { get; set; }
        public Nullable<System.DateTime> saturday_start1 { get; set; }
        public Nullable<System.DateTime> saturday_end1 { get; set; }
        public Nullable<System.DateTime> saturday_start2 { get; set; }
        public Nullable<System.DateTime> saturday_end2 { get; set; }
        public Nullable<System.DateTime> saturday_start3 { get; set; }
        public Nullable<System.DateTime> saturday_end3 { get; set; }
        public Nullable<System.DateTime> holidaytype1_start1 { get; set; }
        public Nullable<System.DateTime> holidaytype1_end1 { get; set; }
        public Nullable<System.DateTime> holidaytype1_start2 { get; set; }
        public Nullable<System.DateTime> holidaytype1_end2 { get; set; }
        public Nullable<System.DateTime> holidaytype1_start3 { get; set; }
        public Nullable<System.DateTime> holidaytype1_end3 { get; set; }
        public Nullable<System.DateTime> holidaytype2_start1 { get; set; }
        public Nullable<System.DateTime> holidaytype2_end1 { get; set; }
        public Nullable<System.DateTime> holidaytype2_start2 { get; set; }
        public Nullable<System.DateTime> holidaytype2_end2 { get; set; }
        public Nullable<System.DateTime> holidaytype2_start3 { get; set; }
        public Nullable<System.DateTime> holidaytype2_end3 { get; set; }
        public Nullable<System.DateTime> holidaytype3_start1 { get; set; }
        public Nullable<System.DateTime> holidaytype3_end1 { get; set; }
        public Nullable<System.DateTime> holidaytype3_start2 { get; set; }
        public Nullable<System.DateTime> holidaytype3_end2 { get; set; }
        public Nullable<System.DateTime> holidaytype3_start3 { get; set; }
        public Nullable<System.DateTime> holidaytype3_end3 { get; set; }
        public Nullable<int> TimeZone1Id { get; set; }
        public Nullable<int> TimeZone2Id { get; set; }
        public Nullable<int> TimeZone3Id { get; set; }
        public Nullable<int> TimeZoneHolidayId { get; set; }
    }
}
