//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public long account_id { get; set; }
        public string account_number { get; set; }
        public string account_name { get; set; }
        public string full_name { get; set; }
        public Nullable<long> parent_account_id { get; set; }
        public string account_type { get; set; }
        public string account_subtype { get; set; }
        public string normal_balance { get; set; }
        public bool allow_posting { get; set; }
        public bool is_active { get; set; }
        public string description { get; set; }
        public string external_source { get; set; }
        public string external_source_id { get; set; }
        public Nullable<System.DateTime> external_time_modified { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<long> external_balance { get; set; }
        public Nullable<long> external_total_balance { get; set; }
    }
}
