//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public string Badge { get; set; }
        public string CardNo { get; set; }
        public string Action { get; set; }
        public string EntryCodes { get; set; }
        public Nullable<int> AuthorizedTimeZone { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public bool IsDirty { get; set; }
    }
}
