
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;

public partial class Communication
{

    public long CommunicationID { get; set; }

    public string Subject { get; set; }

    public System.DateTime SentAt { get; set; }

    public Nullable<int> RecipientCount { get; set; }

    public string Recipient { get; set; }

    public string SentBy { get; set; }

    public Nullable<int> SavedEmailId { get; set; }

}

}
