
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;

public partial class CommunicationEvent
{

    public long EventID { get; set; }

    public long CommunicationID { get; set; }

    public string EventType { get; set; }

    public Nullable<System.DateTime> EventTime { get; set; }

    public string RawPayload { get; set; }

}

}
