
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;
    
public partial class CreditTotal
{

    public int id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<double> Total { get; set; }

    public Nullable<double> Awarded { get; set; }

    public Nullable<double> Used { get; set; }

    public Nullable<double> Diff { get; set; }

    public Nullable<int> FreeDays { get; set; }

    public Nullable<int> ShopUsage { get; set; }

}

}
