//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_movements
    {
        public int movement_id { get; set; }
        public int item_id { get; set; }
        public string movement_type { get; set; }
        public string reference_id { get; set; }
        public string external_txn_id { get; set; }
        public System.DateTime movement_date { get; set; }
        public decimal quantity_change { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string source_system { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
