//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int item_id { get; set; }
        public decimal quantity_on_hand { get; set; }
        public Nullable<System.DateTime> last_sync_time { get; set; }
    }
}
