//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int item_id { get; set; }
        public string item_type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> income_account_id { get; set; }
        public Nullable<int> cogs_account_id { get; set; }
        public Nullable<int> asset_account_id { get; set; }
        public Nullable<decimal> sales_price { get; set; }
        public Nullable<decimal> purchase_cost { get; set; }
        public Nullable<decimal> average_cost { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public Nullable<int> pref_vendor { get; set; }
        public string mfg_part_number { get; set; }
    }
}
