//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinePerm
    {
        public int id { get; set; }
        public string Badge { get; set; }
        public int MachineId { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public bool Blocked { get; set; }
    }
}
