
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;
    
public partial class MailingListMember
{

    public int MailingListMemberId { get; set; }

    public int MailingListId { get; set; }

    public int MemberId { get; set; }

    public System.DateTime AddedAt { get; set; }

    public bool IsSubscribed { get; set; }



    public virtual MailingList MailingList { get; set; }

}

}
