//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRFcard
    {
        public int RECORD_NR { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Badge { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public string RecCard { get; set; }
    }
}
