
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;
    
public partial class MonitorParam
{

    public int Monitor_ID { get; set; }

    public string Monitor_Badge { get; set; }

    public string Monitor_Preferred_Contact { get; set; }

    public string Monitor_Arrive_SCW { get; set; }

    public string Monitor_Depart_SCW { get; set; }

    public string Monitor_Secret { get; set; }

    public string Monitor_Class_Contact { get; set; }

}

}
