
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;

public partial class SavedEmail
{

    public int SavedEmailId { get; set; }

    public string Subject { get; set; }

    public string BodyHtml { get; set; }

    public string FromAddress { get; set; }

    public Nullable<int> MailingListId { get; set; }

    public bool SendToAll { get; set; }

    public string ExtraAddresses { get; set; }

    public bool IsSent { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

}

}
