
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WoodClub
{

using System;
    using System.Collections.Generic;

public partial class SavedEmailAttachment
{

    public int SavedEmailAttachmentId { get; set; }

    public int SavedEmailId { get; set; }

    public string FileName { get; set; }

    public string MimeType { get; set; }

    public byte[] Content { get; set; }

}

}
