//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_zones
    {
        public int id { get; set; }
        public Nullable<int> TimeZone1Id { get; set; }
        public Nullable<int> TimeZone2Id { get; set; }
        public Nullable<int> TimeZone3Id { get; set; }
        public Nullable<bool> TZ1dirty { get; set; }
        public Nullable<bool> TZ2dirty { get; set; }
        public Nullable<bool> TZ3dirty { get; set; }
        public string TZname { get; set; }
        public Nullable<System.DateTime> sunday_start1 { get; set; }
        public Nullable<System.DateTime> sunday_end1 { get; set; }
        public Nullable<System.DateTime> sunday_start2 { get; set; }
        public Nullable<System.DateTime> sunday_end2 { get; set; }
        public Nullable<System.DateTime> sunday_start3 { get; set; }
        public Nullable<System.DateTime> sunday_end3 { get; set; }
        public Nullable<System.DateTime> monday_start1 { get; set; }
        public Nullable<System.DateTime> monday_end1 { get; set; }
        public Nullable<System.DateTime> monday_start2 { get; set; }
        public Nullable<System.DateTime> monday_end2 { get; set; }
        public Nullable<System.DateTime> monday_start3 { get; set; }
        public Nullable<System.DateTime> monday_end3 { get; set; }
        public Nullable<System.DateTime> tuesday_start1 { get; set; }
        public Nullable<System.DateTime> tuesday_end1 { get; set; }
        public Nullable<System.DateTime> tuesday_start2 { get; set; }
        public Nullable<System.DateTime> tuesday_end2 { get; set; }
        public Nullable<System.DateTime> tuesday_start3 { get; set; }
        public Nullable<System.DateTime> tuesday_end3 { get; set; }
        public Nullable<System.DateTime> wednesday_start1 { get; set; }
        public Nullable<System.DateTime> wednesday_end1 { get; set; }
        public Nullable<System.DateTime> wednesday_start2 { get; set; }
        public Nullable<System.DateTime> wednesday_end2 { get; set; }
        public Nullable<System.DateTime> wednesday_start3 { get; set; }
        public Nullable<System.DateTime> wednesday_end3 { get; set; }
        public Nullable<System.DateTime> thursday_start1 { get; set; }
        public Nullable<System.DateTime> thursday_end1 { get; set; }
        public Nullable<System.DateTime> thursday_start2 { get; set; }
        public Nullable<System.DateTime> thursday_end2 { get; set; }
        public Nullable<System.DateTime> thursday_start3 { get; set; }
        public Nullable<System.DateTime> thursday_end3 { get; set; }
        public Nullable<System.DateTime> friday_start1 { get; set; }
        public Nullable<System.DateTime> friday_end1 { get; set; }
        public Nullable<System.DateTime> friday_start2 { get; set; }
        public Nullable<System.DateTime> friday_end2 { get; set; }
        public Nullable<System.DateTime> friday_start3 { get; set; }
        public Nullable<System.DateTime> friday_end3 { get; set; }
        public Nullable<System.DateTime> saturday_start1 { get; set; }
        public Nullable<System.DateTime> saturday_end1 { get; set; }
        public Nullable<System.DateTime> saturday_start2 { get; set; }
        public Nullable<System.DateTime> saturday_end2 { get; set; }
        public Nullable<System.DateTime> saturday_start3 { get; set; }
        public Nullable<System.DateTime> saturday_end3 { get; set; }
    }
}
