//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Badge { get; set; }
        public string RecCard { get; set; }
        public string EventType { get; set; }
        public string Code { get; set; }
        public Nullable<float> CreditAmt { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public int id { get; set; }
    }
}
